### ISSUE TITLE
Double click on any buttons inside the survey is crashing 

### ISSUE THREAD

**Issue by gouravd** [quickbirdstudios/SurveyKit#15]
Some users can double click/tap on buttons inside the survey (like Lets Go or Send survey) and its causing to crash

2020-03-17 17:07:42.381 26534-26534/com.tejimandi.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tejimandi.beta, PID: 26534
    java.lang.IllegalStateException: Already resumed
        at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:45)
        at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$1.invoke(PresenterImpl.kt:62)
        at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$1.invoke(PresenterImpl.kt:17)
        at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$onViewCreated$1.invoke(QuestionView.kt:122)
        at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$onViewCreated$1.invoke(QuestionView.kt:51)
        at com.quickbirdstudios.surveykit.backend.views.main_parts.Footer$$special$$inlined$apply$lambda$1.onClick(Footer.kt:64)
        at android.view.View.performClick(View.java:6319)
        at android.view.View$PerformClick.run(View.java:24955)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
2020-03-17 17:07:42.382 26534-26534/com.tejimandi.beta D/App: Alert Already resumed
2020-03-17 17:07:42.384 26534-26534/com.tejimandi.beta E/Utils: java.lang.IllegalStateException: Already resumed
        at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:45)
        at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$1.invoke(PresenterImpl.kt:62)
        at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$1.invoke(PresenterImpl.kt:17)
        at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$onViewCreated$1.invoke(QuestionView.kt:122)
        at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$onViewCreated$1.invoke(QuestionView.kt:51)
        at com.quickbirdstudios.surveykit.backend.views.main_parts.Footer$$special$$inlined$apply$lambda$1.onClick(Footer.kt:64)
        at android.view.View.performClick(View.java:6319)
        at android.view.View$PerformClick.run(View.java:24955)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by coroutineDispatcher** [comment]
I would like to take over the issue.

**Comment by coroutineDispatcher** [comment]
Hi @gouravd .

Can you share the device you are using the SurveyKit?

**Comment by gouravd** [comment]
I am using Redmi Note 9 but it's reproducible on other devices too (as reported by our tester)

**Comment by coroutineDispatcher** [comment]
I was unable to reproduce the bug in a Pixel 2 emulator. However I'm still dealing with the issue.

**Comment by coroutineDispatcher** [comment]
Even on a very slow transition, a bug like that doesn't occur. Could you reproduce it in your device?

**Comment by gouravd** [comment]
I am able to reproduce on my device... all I am doing is tapping twice (in quick succession) on
 the "Submit Survey" button or "Let's Go" button

**Comment by gouravd** [comment]
Even I am not able to reproduce on Emulator.. but if I try few times (double tapping on "Let's Go" button, I am able to reproduce the crash

**Comment by gouravd** [comment]
and here's stack from Crashlytics

Fatal Exception: java.lang.IllegalStateException: Already resumed
       at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuation.java:45)
       at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$1.invoke(PresenterImpl.java:62)
       at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$1.invoke(PresenterImpl.java:17)
       at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$onViewCreated$1.invoke(QuestionView.java:122)
       at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$onViewCreated$1.invoke(QuestionView.java:51)
       at com.quickbirdstudios.surveykit.backend.views.main_parts.Footer$$special$$inlined$apply$lambda$1.onClick(Footer.java:64)
       at android.view.View.performClick(View.java:6733)
       at android.view.View.performClickInternal(View.java:6691)
       at android.view.View.access$3400(View.java:802)
       at android.view.View$PerformClick.run(View.java:26497)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7179)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

Affected devices

31% samsung
19% vivo
19% Xiaomi
12% OnePlus
19% Other (2)

**Comment by gouravd** [comment]
On debugging myself I realized I was on build 0.1.0, when I upgraded to 1.1.0, the issue was fixed... closing
