### ISSUE TITLE
IllegalStateException when cancelling a questionnaire

### ISSUE THREAD

**Issue by roshanrajaratnam** [quickbirdstudios/SurveyKit#23]
Library throws the following error when trying to cancel a ongoing questionnaire.

```
java.lang.IllegalStateException: Already resumed
        at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:45)
        at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$2.invoke(PresenterImpl.kt:70)
        at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$2.invoke(PresenterImpl.kt:17)
        at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$setupViews$5.invoke(QuestionView.kt:103)
        at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$setupViews$5.invoke(QuestionView.kt:51)
        at com.quickbirdstudios.surveykit.backend.views.main_parts.Header$$special$$inlined$apply$lambda$1.onClick(Header.kt:70)
        at android.view.View.performClick(View.java:7259)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27892)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by KlausNie** [comment]
Can you share the phone and android version where you experience this?

**Comment by roshanrajaratnam** [comment]
@KlausNie I've noticed this on Android 10 as well as on the developer preview on a pixel 3Xl and a 3aXL. Also my questionnaire is on a fragment and I noticed that the sample project uses an activity. Don't think this should be an issue either...

**Comment by KlausNie** [comment]
I'll try to find out if the fragment is the issue, but I also don't think it is.

**Comment by coroutineDispatcher** [comment]
What's the version of the library you are using?

**Comment by roshanrajaratnam** [comment]
0.1.0

**Comment by coroutineDispatcher** [comment]
Do you mind sharing steps to reproduce also?

**Comment by coroutineDispatcher** [comment]
Closing this Issue for now. Please switch to newest version and if you encounter the problem again, please let us know in a new issue.
