### ISSUE TITLE
IllegalStateException: Already resumed

### ISSUE THREAD

**Issue by sellmair** [quickbirdstudios/SurveyKit#9]
Just click through the example app. 
Submit Survey Button seems to do nothing on first click, the second click will lead to the following stacktrace
```
2019-11-27 11:31:04.037 16930-16930/com.quickbirdstudios.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.quickbirdstudios.example, PID: 16930
    java.lang.IllegalStateException: Already resumed
        at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:45)
        at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$1.invoke(PresenterImpl.kt:62)
        at com.quickbirdstudios.surveykit.backend.presenter.PresenterImpl$showAndWaitForResult$$inlined$suspendCoroutine$lambda$1.invoke(PresenterImpl.kt:17)
        at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$onViewCreated$1.invoke(QuestionView.kt:122)
        at com.quickbirdstudios.surveykit.backend.views.step.QuestionView$onViewCreated$1.invoke(QuestionView.kt:51)
        at com.quickbirdstudios.surveykit.backend.views.main_parts.Footer$$special$$inlined$apply$lambda$1.onClick(Footer.kt:64)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by KlausNie** [comment]
The first click actually finishes the survey, it would be the developers task, to change the screen.

Now I just remove the survey, since

**Comment by wangwei01** [comment]
i get same error .can you solve it.

**Comment by johnnyriver90** [comment]
I Have this issue. anyone help me

  java.lang.IllegalStateException: Already resumed, but proposed with update kotlin.Unit
        at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:332)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:327)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:247)
        at com.justai.aimybox.speechkit.google.platform.GooglePlatformTextToSpeech$speak$2$invokeSuspend$$inlined$suspendCancellableCoroutine$lambda$2.onStop(GooglePlatformTextToSpeech.kt:60)
        at android.speech.tts.TextToSpeech$Connection$1.onStop(TextToSpeech.java:2119)
        at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:74)
        at android.os.Binder.execTransact(Binder.java:731)
